name: vertical_card_pager
description: Use dynamic and beautiful card view pagers to help you create great apps.
version: 1.6.0+1
homepage: https://origogi.github.io/
repository: https://github.com/Origogi/Vertical_Card_Pager
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: Vertical Card Pager Example
    path: screenshot/screenshot.png